apiVersion: v1
kind: service
metadata:
  name: portfolio-service
spec:
  type: LoadBalancer
    selector:
        app: portfolio-app
    ports:
        - protocol: TCP
        port: 80
        targetPort: 80
